// Central catalogue of `IdpError.code` values this package throws.
// Not exhaustive-enforced — a stable reference for consumers writing their
// error-handling middleware.
export const ERROR_CODES = Object.freeze({
    // Generic
    INTERNAL_ERROR: 'INTERNAL_ERROR',
    INVALID_REQUEST: 'INVALID_REQUEST',
    MISSING_REQUIRED_FIELDS: 'MISSING_REQUIRED_FIELDS',
    VALIDATION_ERROR: 'VALIDATION_ERROR',
    SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
    NOT_FOUND: 'NOT_FOUND',
    RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',

    // AuthN
    AUTH_REQUIRED: 'AUTH_REQUIRED',
    UNAUTHENTICATED: 'UNAUTHENTICATED',
    FORBIDDEN: 'FORBIDDEN',
    INVALID_TOKEN: 'INVALID_TOKEN',
    TOKEN_EXPIRED: 'TOKEN_EXPIRED',
    TOKEN_REVOKED: 'TOKEN_REVOKED',
    CACHE_UNAVAILABLE: 'CACHE_UNAVAILABLE',

    // Credentials / account lifecycle
    INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
    EMAIL_AND_PASSWORD_REQUIRED: 'EMAIL_AND_PASSWORD_REQUIRED',
    EMAIL_REQUIRED: 'EMAIL_REQUIRED',
    USER_NOT_FOUND: 'USER_NOT_FOUND',
    USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
    USER_NOT_ACTIVE: 'USER_NOT_ACTIVE',
    ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
    ACCOUNT_SUSPENDED: 'ACCOUNT_SUSPENDED',
    PENDING_VERIFICATION: 'PENDING_VERIFICATION',
    CANNOT_DELETE_USER: 'CANNOT_DELETE_USER',
    EMAIL_ALREADY_VERIFIED: 'EMAIL_ALREADY_VERIFIED',
    INVALID_OR_EXPIRED_TOKEN: 'INVALID_OR_EXPIRED_TOKEN',
    CURRENT_PASSWORD_INCORRECT: 'CURRENT_PASSWORD_INCORRECT',

    // Refresh / session
    REFRESH_TOKEN_REQUIRED: 'REFRESH_TOKEN_REQUIRED',
    INVALID_REFRESH_TOKEN: 'INVALID_REFRESH_TOKEN',
    REFRESH_TOKEN_NOT_FOUND: 'REFRESH_TOKEN_NOT_FOUND',

    // MFA
    MFA_ALREADY_ENABLED: 'MFA_ALREADY_ENABLED',
    MFA_NOT_ENABLED: 'MFA_NOT_ENABLED',
    MFA_SETUP_REQUIRED: 'MFA_SETUP_REQUIRED',
    INVALID_MFA_CODE: 'INVALID_MFA_CODE',
    INVALID_MFA_CHALLENGE_TOKEN: 'INVALID_MFA_CHALLENGE_TOKEN',

    // OAuth2 / OIDC / JWKS
    UNKNOWN_KID: 'UNKNOWN_KID',
    KEY_NOT_ALLOWED: 'KEY_NOT_ALLOWED',
    INVALID_REDIRECT_URI: 'INVALID_REDIRECT_URI',

    // SSO
    SSO_PROVIDER_ERROR: 'SSO_PROVIDER_ERROR',
    INVALID_SSO_PROVIDER: 'INVALID_SSO_PROVIDER',
    SSO_PROVIDER_NOT_CONFIGURED: 'SSO_PROVIDER_NOT_CONFIGURED',
    INVALID_SSO_STATE: 'INVALID_SSO_STATE',

    // OAuth clients / tenants
    OAUTH_CLIENT_EXISTS: 'OAUTH_CLIENT_EXISTS',
    OAUTH_CLIENT_NOT_FOUND: 'OAUTH_CLIENT_NOT_FOUND',

    // Service mesh
    SERVICE_TOKEN_INVALID: 'SERVICE_TOKEN_INVALID',
    SERVICE_AUTH_FAILED: 'SERVICE_AUTH_FAILED',
    SERVICE_NOT_CONFIGURED: 'SERVICE_NOT_CONFIGURED',

    // WebAuthn / passkeys
    WEBAUTHN_NOT_CONFIGURED: 'WEBAUTHN_NOT_CONFIGURED',
    WEBAUTHN_CHALLENGE_EXPIRED: 'WEBAUTHN_CHALLENGE_EXPIRED',
    WEBAUTHN_VERIFICATION_FAILED: 'WEBAUTHN_VERIFICATION_FAILED',
    CREDENTIAL_NOT_FOUND: 'CREDENTIAL_NOT_FOUND',
});
